{{ range $index, $project := .Values.projects }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ $project.name }}
---

  {{- range $index, $ns := .namespaces -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $project.name }}-{{ $ns }}
---
  {{- end }}

{{- end }}